### ISSUE TITLE
solve s3 list download 

### ISSUE THREAD

**Issue by Schuler-Gabriel** [tiki/publish-data-receipt#10]
### Reason

we need to solve the s3 list download to be able to download the receipts

### Description

currently the request for the list is getting an error, probably due to some autentication issue.
the code already deals with the json array creation and byte array to json conversion.
the code have the function to download the receipt listed in the list, but needs testing 

### Success Criteria

- [ ] all working

**Comment by ricardobrg** [comment]
closed in #9
