### ISSUE TITLE
Build a lambda function to create the Receipt Data Response

### ISSUE THREAD

**Issue by MiroBenicio** [tiki/publish-data-receipt#7]
### Reason

Build the get receipt data infrastructure

### Description

We should build a lambda function in AWS, using RUST.

this function, will receive the receive the receipt id as an input. Tho, it should query to S3 and get every formatted JSON related to that id, join everything in only one array in a JSON and return it to the client-side

### Success Criteria

- [ ] A lambda function which returns the correct JSON as output

**Comment by ricardobrg** [comment]
closed in #9
